module.exports = {
  url: "https://twoimo.github.io/",
  pathPrefix: "/",
  title: "@twoimo",
  subtitle: "Yeonwoo Choi",
  copyright: "© All rights reserved.",
  disqusShortname: "",
  postsPerPage: 4,
  useKatex: false,
  menu: [
    {
      label: "Articles",
      path: "/",
    },
    {
      label: "About me",
      path: "/pages/about",
    },
    {
      label: "Research",
      path: "/pages/research",
    },
  ],
  author: {
    name: "Yeonwoo Choi",
    photo: "/photo.jpg",
    bio: "Yeonwoo Choi",
    contacts: {
      email: "kss2740@naver..com",
      facebook: "twoimo",
      telegram: "twoimo",
      twitter: "twoimo_",
      github: "twoimo",
      rss: "",
      vkontakte: "",
      linkedin: "",
      instagram: "",
      line: "",
      gitlab: "",
      weibo: "",
      codepen: "",
      soundcloud: "",
      medium: "",
    },
  },
};
